version: "3.8"

services:
  chirpstack:
    image: chirpstack/chirpstack:4
    depends_on:
      - postgres
      - redis
      - mosquitto
    ports:
      - "8080:8080"
    volumes:
      - "./chirpstack:/etc/chirpstack"
    command:
      - "chirpstack"
      - "--config"
      - "/etc/chirpstack"
    restart: unless-stopped

  gateway-bridge:
    image: chirpstack/chirpstack-gateway-bridge:4
    depends_on:
      - mosquitto
    ports:
      - "1700:1700/udp"
    volumes:
      - "./chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge"
    command:
      - "chirpstack-gateway-bridge"
      - "--config"
      - "/etc/chirpstack-gateway-bridge"
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: chirpstack
      POSTGRES_PASSWORD: change_me_strong
      POSTGRES_DB: chirpstack
    volumes:
      - "postgresdata:/var/lib/postgresql/data"
      - "./.docker-compose/postgresql/initdb:/docker-entrypoint-initdb.d"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
    volumes:
      - "./.docker-compose/mosquitto/config:/mosquitto/config"
      - "mosquitto_data:/mosquitto/data"
      - "mosquitto_log:/mosquitto/log"
    restart: unless-stopped

volumes:
  postgresdata:
  mosquitto_data:
  mosquitto_log:
