# /etc/chirpstack-gateway-bridge/chirpstack-gateway-bridge.toml

[general]
log_level=4

[backend]
type="semtech_udp"

[backend.semtech_udp]
udp_bind="0.0.0.0:1700"

[integration]
marshaler="json"

[integration.mqtt]
server="tcp://mosquitto:1883"

environment:
INTEGRATION__MQTT__SERVER=tcp://mosquitto:1883

event_topic_template="eu868/gateway/{{ .GatewayID }}/event/{{ .EventType }}"
command_topic_template="eu868/gateway/{{ .GatewayID }}/command/#"
