# /etc/chirpstack/chirpstack.toml

[logging]
level = "info"

[postgresql]
dsn = "postgres://chirpstack:change_me_strong@postgres/chirpstack?sslmode=disable"

[redis]
servers = ["redis://redis:6379/"]
cluster = false

[network]
net_id = "000000"
enabled_regions = ["eu868"]

[api]
bind = "0.0.0.0:8080"
secret = "uzuMDt2hKI9TEvtYNWxRhzWyHeLrQB6FUpRUhgYW4kw="

# ------------------------------------------------------------
# Application integration (events to your apps) via MQTT
# ------------------------------------------------------------
[integration]
enabled = ["mqtt"]

[integration.mqtt]
server = "tcp://mosquitto:1883"
json = true
qos = 0
clean_session = false
keep_alive_interval = "30s"
client_id = "chirpstack-app"
# username = "xxxx"      # si auth activée côté mosquitto
# password = "xxxx"

# ------------------------------------------------------------
# Gateway backend (uplinks/downlinks with gateways) via MQTT
# ------------------------------------------------------------
[gateway]
[gateway.backend]
[gateway.backend.mqtt]
server = "tcp://mosquitto:1883"
qos = 0
clean_session = false
keep_alive_interval = "30s"
client_id = "chirpstack-gw"
# username = "xxxx"      # si auth activée côté mosquitto
# password = "xxxx"
